name: Run Tests and Generate Allure Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      
      # Run API Tests
      - name: Run API Tests
        run: |
          mvn clean test -Dtest="*APITests"

      # Save Allure results as artifacts
      - name: Archive Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: target/allure-results

  run-ui-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run UI Tests
        run: |
          mvn test -Dtest="**/*Test.java" -DfailIfNoTests=true

      # Save Allure results as artifacts
      - name: Archive Allure Results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-ui
          path: target/allure-results

  generate-allure-report:
    runs-on: ubuntu-latest
    needs: [run-api-tests, run-ui-tests]
    if: always()
    
    steps:
      - uses: actions/checkout@v3
      
      # Download and set up Allure
      - name: Download Allure CommandLine
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.24.1/allure-2.24.1.tgz
          sudo tar -zxvf allure-2.24.1.tgz -C /opt/
          sudo ln -s /opt/allure-2.24.1/bin/allure /usr/bin/allure
          allure --version

      # Download Allure results artifacts
      - name: Download Allure API Results
        uses: actions/download-artifact@v3
        with:
          name: allure-results
          path: allure-results-api

      - name: Download Allure UI Results
        uses: actions/download-artifact@v3
        with:
          name: allure-results-ui
          path: allure-results-ui

      # Generate environment.properties
      - name: Generate Environment Properties
        run: |
          mkdir -p combined-allure-results
          echo "Browser=Chrome" > combined-allure-results/environment.properties
          echo "Browser.Version=latest" >> combined-allure-results/environment.properties
          echo "Environment=QA" >> combined-allure-results/environment.properties

      # Merge and Generate Allure report
      - name: Generate Allure Report
        run: |
          cp -R allure-results-api/* combined-allure-results/
          cp -R allure-results-ui/* combined-allure-results/
          allure generate combined-allure-results --clean -o allure-report

      # Upload Allure report as an artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
          retention-days: 30