name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Use Eclipse Temurin (AdoptOpenJDK)
          java-version: '17'      # Ensure compatibility with your project's SDK

      # Start the backend service using Java SDK
      - name: Start Backend Service
        run: |
          nohup java -jar libs/demo-0.0.1-SNAPSHOT.jar &

      # Wait for the backend service to start
      - name: Wait for backend
        run: |
          for i in {1..10}; do
            nc -zv localhost 7081 && echo "Backend is up!" && break
            echo "Waiting for backend..."
            sleep 5
          done

      # Run API Tests
      - name: Run API Tests
        run: |
          mvn test -Dtest="com.selenium.testing.apiTesting.tests.registerBookApiTest.BookAPITest"

  ui-tests:
    runs-on: ubuntu-latest
    needs: run-tests

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Install Chrome and WebDriver for UI tests
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Chrome WebDriver
        run: |
          wget -N https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/local/bin

      # Run UI Tests
      # - name: Run UI Tests
      #   run: |
      #     mvn -Dtest="com.selenium.testing.uiTesting.*" test
